#!/bin/sh

case $1 in
     start)
          fallocate -l 60M /swapfile
          chmod 0600 /swapfile
          mkswap /swapfile
          swapon  /swapfile
     ;;
     stop)
          swapoff /swapfile
          rm /swapfile
     ;;
esac
