#!/bin/sh

# Usage: xbt-init [batch_number]

set -e

if [[ ! -e /srv/xbterminal/xbterminal/runtime/batch_number ]]
then
    if [[ "$XBT_INIT_PRODUCTION_MODE" = true ]]
    then
        # Started as systemd service (core-image-xbt image)
        BATCH_NUMBER=$(wget https://xbterminal.io/api/v2/batches/current/ -q -O -)
    else
        # Manual execution (core-image-xbt-dev image)
        BATCH_NUMBER=${1:-"00000000000000000000000000000000"}
    fi

    # Write batch number
    echo $BATCH_NUMBER > /srv/xbterminal/xbterminal/runtime/batch_number
    echo "Batch number ${BATCH_NUMBER}"

    # Generate device key and write minion id
    DEVICE_KEY=`cat /etc/machine-id | sha256sum | cut -d " " -f 1`
    echo $DEVICE_KEY > /srv/xbterminal/xbterminal/runtime/device_key
    echo $DEVICE_KEY > /etc/salt/minion_id
    echo "New device key ${DEVICE_KEY}"

    if [[ "$BATCH_NUMBER" = "00000000000000000000000000000000" ]]
    then
        # Use dev server; don't run firmware
        echo -e "{\n    \"remote_server\": \"stage\"\n}" > /srv/xbterminal/xbterminal/runtime/local_config
        echo "environment: stage" > /etc/salt/minion.d/env.conf
    fi

    # Restart salt-minion
    systemctl restart salt-minion

    # Run touchscreen calibrator if present
    if [[ -e /usr/bin/xinput_calibrator_once.sh ]]
    then
        xinit xinput_calibrator_once.sh &> /dev/null
    fi

    echo "Device successfully initialized"
else
    echo "Device already initialized, exiting"
fi
